### ISSUE TITLE
The generated resolveIds are not absolute paths, and thus do not match relative imports.

### ISSUE THREAD

**Issue by taylorhadden** [Hedzer/rollup-plugin-import-alias#5]
Hello,

I found a bug where an aliased import and a relative import ostensibly to the same file actually appeared to point at different files.

Say I have a project structure:

```
my_modules/
  bar.js
src/
  test.js
```

bar.js:
```js
class Bar {
}
export default Bar
```

And I have an alias set up like this:

```js
alias({
  Paths: {
    'bar': './my_modules/bar'
  }
})
```

Then the following will occur in `test.js`:

```js
import bar from 'bar'
import bar2 from '../my_modules/bar'

console.log(bar === bar2) // prints "false"
```

This is because rollup by default resolves ids to absolute file paths with `path.resolve()`. With different resolveIds, the two imports resolve as completely different modules, with different side effects and class definitions. In my limited testing, I was able to fix this by wrapping line #28 in import-alias' `index.js`:

```js
// from
var directory = importee.replace(entry.key, entry.path);
// to
var directory = path.resolve(importee.replace(entry.key, entry.path));
```

This means that the aliased import and the relative import will point to the same files, and rollup will resolve both imports as the same module.

**Comment by Hedzer** [comment]
Hey Taylor, thank you for feedback. I think at this point I need to build some tests and do some refactoring. This might take me a little. I apologize for the delay. I'm working to remedy this issue.

**Comment by taylorhadden** [comment]
No worries! I ended up getting something set up locally for me. I can share if you like.

**Comment by Hedzer** [comment]
oh gosh, I am so sorry about the delay. I started to refactor and add tests and totally forgot about it after the memorial service (grandparents).

I'm definitely interested in your solution. Was it just adding path.resolve or were there other changes? I'm a little worried that a quick merge & publish will break other people's projects (hence, adding tests). What kinds of usage is it getting in your project? I think you had mentioned both relative and absolute roots.

This little plugin went from something I cooked up quick for myself to getting more attention than I anticipated. Needless to say it needs TLC.

**Comment by Hedzer** [comment]
@taylorhadden I published a new version with the path.resolve fix. I decided to just test it with my local builds. Since that's not a super comprehensive way to test things, I hope I don't accidentally break other builds with the changes.  I'm postponing the tests and rewrite until I have the proper time to do it.
